######################################################################
# Automatically generated by qmake (3.1) Tue Apr 15 10:38:59 2025
######################################################################

TEMPLATE = app
TARGET = QtLibrary
INCLUDEPATH += .
QT += widgets 

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += Headers/GUI/advancedSearch.h \
           Headers/GUI/animeFilters.h \
           Headers/GUI/app.h \
           Headers/GUI/bookFilters.h \
           Headers/GUI/creation.h \
           Headers/GUI/filmFilters.h \
           Headers/GUI/genericFilters.h \
           Headers/GUI/mainwindow.h \
           Headers/GUI/mangaFilters.h \
           Headers/GUI/search.h \
           Headers/LogicModel/anime.h \
           Headers/LogicModel/contenuto.h \
           Headers/LogicModel/digitale.h \
           Headers/LogicModel/film.h \
           Headers/LogicModel/fisico.h \
           Headers/LogicModel/libro.h \
           Headers/LogicModel/manga.h \
           Headers/LogicModel/periodico.h \
           Headers/LogicModel/visitors.h \
           Sources/JSON/JsonHandler.hpp
SOURCES += main.cpp \
           Sources/GUI/advancedSearch.cpp \
           Sources/GUI/animeFilters.cpp \
           Sources/GUI/app.cpp \
           Sources/GUI/bookFilters.cpp \
           Sources/GUI/creation.cpp \
           Sources/GUI/filmFilters.cpp \
           Sources/GUI/genericFilter.cpp \
           Sources/GUI/mainwindow.cpp \
           Sources/GUI/mangaFilters.cpp \
           Sources/GUI/search.cpp \
           Sources/LogicModel/anime.cpp \
           Sources/LogicModel/contenuto.cpp \
           Sources/LogicModel/digitale.cpp \
           Sources/LogicModel/film.cpp \
           Sources/LogicModel/fisico.cpp \
           Sources/LogicModel/libro.cpp \
           Sources/LogicModel/manga.cpp \
           Sources/LogicModel/periodico.cpp

OBJECTS_DIR = build/objects

MOC_DIR = build/moc
