######################################################################
# Automatically generated by qmake (3.1) Wed Jun 4 15:03:29 2025
######################################################################

TEMPLATE = app
TARGET = QtLibrary
INCLUDEPATH += .
QT += widgets
QT += gui

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += Headers/GUI/animeFilters.h \
           Headers/GUI/app.h \
           Headers/GUI/bookFilters.h \
           Headers/GUI/contentViewer.h \
           Headers/GUI/creation.h \
           Headers/GUI/duplicateVerifier.h \
           Headers/GUI/error.h \
           Headers/GUI/filmFilters.h \
           Headers/GUI/filterVisitor.h \
           Headers/GUI/genericFilters.h \
           Headers/GUI/guiVisitor.h \
           Headers/GUI/indexVisitor.h \
           Headers/GUI/mainWidgets.h \
           Headers/GUI/mainWindow.h \
           Headers/GUI/mangaFilters.h \
           Headers/GUI/research.h \
           Headers/GUI/search.h \
           Headers/GUI/viewContents.h \
           Headers/JSON/jsonSelector.h \
           Headers/LogicModel/anime.h \
           Headers/LogicModel/checkVisitor.h \
           Headers/LogicModel/contentManager.h \
           Headers/LogicModel/contenuto.h \
           Headers/LogicModel/creationVisitor.h \
           Headers/LogicModel/digitale.h \
           Headers/LogicModel/film.h \
           Headers/LogicModel/fisico.h \
           Headers/LogicModel/libro.h \
           Headers/LogicModel/manga.h \
           Headers/LogicModel/periodico.h \
           Headers/LogicModel/searchVisitor.h \
           Headers/LogicModel/visitors.h \
           Sources/JSON/JsonHandler.hpp
SOURCES += main.cpp \
           Sources/GUI/animeFilters.cpp \
           Sources/GUI/app.cpp \
           Sources/GUI/bookFilters.cpp \
           Sources/GUI/contentViewer.cpp \
           Sources/GUI/creation.cpp \
           Sources/GUI/duplicateVerifier.cpp \
           Sources/GUI/error.cpp \
           Sources/GUI/filmFilters.cpp \
           Sources/GUI/filterVisitor.cpp \
           Sources/GUI/genericFilter.cpp \
           Sources/GUI/indexVisitor.cpp \
           Sources/GUI/mainWidgets.cpp \
           Sources/GUI/mainWindow.cpp \
           Sources/GUI/mangaFilters.cpp \
           Sources/GUI/research.cpp \
           Sources/GUI/search.cpp \
           Sources/GUI/viewContents.cpp \
           Sources/JSON/jsonSelector.cpp \
           Sources/LogicModel/anime.cpp \
           Sources/LogicModel/checkVisitor.cpp \
           Sources/LogicModel/contentManager.cpp \
           Sources/LogicModel/contenuto.cpp \
           Sources/LogicModel/creationVisitor.cpp \
           Sources/LogicModel/digitale.cpp \
           Sources/LogicModel/film.cpp \
           Sources/LogicModel/fisico.cpp \
           Sources/LogicModel/libro.cpp \
           Sources/LogicModel/manga.cpp \
           Sources/LogicModel/periodico.cpp \
           Sources/LogicModel/searchVisitor.cpp
OBJECTS_DIR = build/objects

MOC_DIR = build/moc
